<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => '住所',
    'All rights reserved' => '著作権者',
    'Bạn không có quyền truy cập trang này' => 'このページにアクセスする権限がありません',
    'Bạn đang đăng nhập! Vui lòng thoát ra để thực hiện tính năng này!' => 'ログインしています。この機能を実行するには終了してください。',
    'Chi tiết' => '詳細',
    'Copyright' => '著作権',
    'Công việc' => '仕事',
    'Công việc yêu thích' => '好きな仕事',
    'Cung ứng nhân lực' => '人材派遣',
    'Cảm ơn quý khách đã liên hệ! Chúng tôi sẽ phản hồi lại sớm nhất có thể!' => 'お問い合わせありがとうございます。迅速に対応いたします。',
    'Dịch vụ' => 'サビース',
    'Email' => 'メール',
    'Giá trị cốt lõi' => 'コアバリュー',
    'Giới thiệu' => '紹介',
    'Gửi' => '送信する',
    'Gửi liên hệ' => '連絡を送る',
    'Gửi Ý Kiến' => 'コメントを送る',
    'Họ và tên' => '氏名',
    'ID' => 'ID',
    'Khác' => '他',
    'Lao động' => '労働',
    'Liên hệ' => '連絡',
    'Mã xác nhận' => '確認コード',
    'Mật khẩu cũ' => '旧パスワード',
    'Mật khẩu của bạn đã được khôi phục thành công!' => 'パスワードがリセットされました。',
    'Mật khẩu mới' => '新しいパスワード',
    'Nhập khẩu' => '輸入',
    'Nhập lại mật khẩu mới' => '新しいパスワード（確認）',
    'Nội dung' => '内容',
    'Other posts' => '他の投稿',
    'Similar Products' => '同様の製品',
    'Số hỗn hợp' => 'CVT',
    'Số sàn' => 'MT',
    'Số tự động' => 'AT',
    'Số điện thoại' => '電話番号',
    'Thông báo tuyển dụng' => '採用通知書',
    'Thương mại' => '貿易',
    'Tin tức' => 'ニュース',
    'Trang chủ' => 'ホームページ',
    'Trụ sở chính' => '本社',
    'Tìm kiếm' => '検索',
    'Tư vấn thiết kế, xây dựng' => '設計・施工のコンサルティング',
    'Tư vấn đầu tư' => '投資のコンサルティング',
    'Tầm nhìn sứ mệnh' => '企業理念',
    'Về chúng tôi' => '私たちについて',
    'Xin cấp phép' => '許可申請',
    'Ý kiến của Quý Khách đã được ghi nhận. Chúng tôi sẽ phản hồi sớm! Xin cảm ơn!' => 'コメントが登録されました。迅速に対応いたします。ありがとうございます。',
    'Đang cập nhật!' => '更新中！',
    'Đóng' => '閉める',
    'Địa chỉ' => 'アドレス',
    'Địa điểm' => '場所',
    'Đối tác' => 'パートナー',
];
