<?php
return [
    // Ten he thong
    'system_name' => 'CMS',
    'short_system_name' => 'CMS',

    'sms_shortcode' => 9005,

    'default_content_lang' => 'en',
    'content_languages' => [
        'en' => Yii::t('backend', 'English'),
        'es' => Yii::t('backend', 'Vietnamese'),
    ],
    'position' => [
        '1' => 'Bưu tá',
        '2' => 'Nhân viên nghiệp vụ',
        '3' => 'Nhân viên CSKH',
        '4' => 'Nhân viên bán hàng',
        '5' => 'Nhân viên Đối soát',
        '6' => 'Nhân viên Thanh toán',
    ],
    'mission' => [
        '1' => 'Thu gom',
        '2' => 'Phát',
        '3' => 'Đối soát',
        '4' => 'Thanh toán',
        '5' => 'CSKH',
        '6' => 'Miss Queue',
        null => 'Null',
    ],
    'gender' => [
        '0' => 'Male',
        '1' => 'Female',
        '2' => 'Other',
        null => 'Null',
    ],
    'status5' => [
        null => 'No process',
        '0' => 'No process',
        '1' => 'Processing',
        '2' => 'Sent',
        '3' => 'Over time',
    ],
    'status4' => [
        '1' => 'thugom',
        '2' => 'phat',
        '3' => 'doisoat',
        '4' => 'thanhtoan',
        '5' => 'cskh',
        '6' => 'missqueue',
    ],
    'status3' => [
        '1' => 'Bưu Cục',
        '2' => 'CSKH',
    ],
    'status2' => [
        '0' => 'Inactive',
        '1' => 'Active',
    ],
    'status1' => [
        '1' => 'Working',
        '2' => 'Retired',
    ],
    'status' => [
        '1' => 'questions with answers',
        '2' => 'question has no answer',
    ],
    'statusQueue' => [
        '0' => 'Active',
        '1' => 'Inactive',
    ],
    'province' => [
        '10' => 'Hà Nội',
        '16' => 'Hưng Yên',
        '30' => 'Tuyên Quang',
        '18' => 'Hải Phòng',
        '28' => 'Vĩnh Phúc',
        '52' => 'Quảng Trị',
        '42' => 'Nam Định',
        '44' => 'Thanh Hóa',
        '82' => 'Bình Dương',
        '43' => 'Ninh Bình',
        '53' => 'Huế',
        '65' => 'Khánh Hòa',
        '97' => 'Cà Mau',
        '90' => 'Cần Thơ',
        '09' => 'TMĐT Hà Nội',
        '51' => 'Quảng Bình',
        '38' => 'Điện Biên',
        '39' => 'Lai Châu',
        '46' => 'Nghệ An',
        '63' => 'Đắk Lắk',
        '56' => 'Quảng Nam',
        '60' => 'Gia Lai',
        '22' => 'Bắc Ninh',
        '80' => 'Bình Thuận',
        '81' => 'Đồng Nai',
        '86' => 'Tiền Giang',
        '31' => 'Hà Giang',
        '84' => 'Tây Ninh',
        '25' => 'Thái Nguyên',
        '35' => 'Hòa Bình',
        '41' => 'Thái Bình',
        '83' => 'Bình Phước',
        '89' => 'Vĩnh Long',
        '87' => 'Đồng Tháp',
        '95' => 'Sóc Trăng',
        '70' => 'Hồ Chí Minh',
        '96' => 'Bạc Liêu',
        '92' => 'Kiên Giang',
        '85' => 'Long An',
        '93' => 'Bến Tre',
        '29' => 'Phú Thọ',
        '79' => 'Bà Rịa Vũng Tàu',
        '17' => 'Hải Dương',
        '94' => 'Trà Vinh',
        '26' => 'Bắc Kạn',
        '91' => 'Hậu Giang',
        '88' => 'An Giang',
        '55' => 'Đà Nẵng',
        '59' => 'Bình Định',
        '23' => 'Bắc Giang',
        '36' => 'Sơn La',
        '33' => 'Lào Cai',
        '57' => 'Quảng Ngãi',
        '27' => 'Cao Bằng',
        '40' => 'Hà Nam',
        '20' => 'Quảng Ninh',
        '64' => 'Đắk Nông',
        '32' => 'Yên Bái',
        '66' => 'Ninh Thuận',
        '48' => 'Hà Tĩnh',
        '67' => 'Lâm Đồng',
        '58' => 'Kon Tum',
        '24' => 'Lạng Sơn',
        '62' => 'Phú Yên',
        '' => 'Chưa có',
        null => 'Chưa có',
    ],

    'province_tt' => [
        '0' => '00',
        '1' => '10',
        '2' => '16',
        '3' => '17',
        '4' => '18',
        '5' => '20',
        '6' => '22',
        '7' => '23',
        '8' => '24',
        '9' => '25',
        '10' => '26',
        '11' => '27',
        '12' => '28',
        '13' => '29',
        '14' => '30',
        '15' => '31',
        '16' => '32',
        '17' => '33',
        '18' => '35',
        '19' => '36',
        '20' => '38',
        '21' => '39',
        '22' => '40',
        '23' => '41',
        '24' => '42',
        '25' => '43',
        '26' => '44',
        '27' => '46',
        '28' => '48',
        '29' => '51',
        '30' => '52',
        '31' => '53',
        '32' => '55',
        '33' => '56',
        '34' => '57',
        '35' => '58',
        '36' => '59',
        '37' => '60',
        '38' => '62',
        '39' => '63',
        '40' => '64',
        '41' => '65',
        '42' => '66',
        '43' => '67',
        '44' => '70',
        '45' => '79',
        '46' => '80',
        '47' => '81',
        '48' => '82',
        '49' => '83',
        '50' => '84',
        '51' => '85',
        '52' => '86',
        '53' => '87',
        '54' => '88',
        '55' => '89',
        '56' => '90',
        '57' => '91',
        '58' => '92',
        '59' => '93',
        '60' => '94',
        '61' => '95',
        '62' => '96',
        '63' => '97',
        '64' => '09',
    ],

    'rabbitmq_config' => [
        'host' => '103.143.206.63',
        'port' => 5672,
        'user' => 'admin',
        'password' => 'admin@123',
        'mt_queue_name' => 'test',
    ],

    'bts_code_pattern' => '/^[A-Za-z0-9_]+$/',


    'country_code' => '51',
    'phonenumber_pattern' => '/^(\+51|51|0|)([0-9]{9})$/',
    'phonenum_list_pattern' => '/^\s*(\+51|51|0|)([0-9]{9})(\,\s*(\+51|51|0|)([0-9]{9})(\s*))*$/',
    'deeplink_pattern' => '/^([a-zA-Z])+[a-zA-Z0-9]:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}(\.[a-z]{2,4}\b)?([-a-zA-Z0-9@:%_\+.~#?&\/=]*)$/',

    'adv_channel' => [
        'all' => 'Toàn bộ',
        'web' => 'Web',
        'wap' => 'Wap',
    ],

    'adv_position' => [
        'slideshow' => 'Slideshow',
//        'head_line' => 'Head line',
//        'popup' => 'Popup',
//        'left_banner' => 'Banner bên trái',
//        'right_banner' => 'Banner bên phải',
    ],


    'image_upload_size' => '2', // Dung luong upload file anh tinh theo MB
    // Ten folder luu anh dai dien cua tin tuc, neu ko cau hinh thi he thong se lay dua theo ten model tuong ung
    // Cau hinh dong theo format, $tenModel_image_folder, vi du: post_image_folder
    'current_media_folder' => 'medias', // Ten folder se luu cac file media upload len o thu muc web
    'advertisment_image_folder' => 'hot-image',
    'category_image_folder' => 'category',
    'channel_image_folder' => 'channel',
    'banner_image_folder' => 'banner',
    'video_image_folder' => 'video-images',
    'welcomepage_image_folder' => '/medias/file/welcompage/',
    'image_thumb_image_folder' => 'image-thumbnail',
    'digital_service_image_folder' => 'digital-service',


    'no_image' => '/img/no-image-square.jpg',
    'no_image_16_9' => '/img/no-image-16x9.jpg',
    'banner_locations' => [
        '0' => 'HOME_SLIDE'
    ],

    // Cau hinh google captcha
    'recaptcha_secret' => '6LdUptESAAAAAOYpLj5TbQBPzwzKyCCJj9PKY7ZQ',
    'recaptcha_site_key' => '6LdUptESAAAAAHvd3-ZoYINx2_Aem5hWAqc4weps',

    'adminEmail' => 'admin@example.com',
    'supportEmail' => 'support@example.com',
    'user.passwordResetTokenExpire' => 3600,
];
