<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Authorization code is required' => '',
    'Client id and Client secret is required' => '',
    'Hệ thống đang bận, vui lòng thử lại sau.' => '',
    'Invalid authorization code' => '',
    'Invalid input parameter' => '',
    'Invalid username password' => '',
    'Need permission to execute function.' => '',
    'Need post method to execute function.' => '',
    'Require login.' => '',
    'Successful' => '',
    'Unknown Error' => '',
    'Unknown method' => '',
    'Username and Password is required' => '',
    'Wrong client id and client secret' => '',
    'You are not authorized to perform this action' => '',
    'Your account is locked' => '',
    'Your account is not active' => '',
    'Created At' => '@@@@',
    'ID' => '@@@@',
    'Image Path' => '@@@@',
    'Music Genre ID' => '@@@@',
    'Position' => '@@@@',
    'Priority' => '@@@@',
    'Rank ID' => '@@@@',
    'Singer ID' => '@@@@',
    'Song ID' => '@@@@',
    'Updated At' => '@@@@',
    'Video ID' => '@@@@',
];
