<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => '',
    'All rights reserved' => '',
    'Bạn không có quyền truy cập trang này' => '',
    'Bạn đang đăng nhập! Vui lòng thoát ra để thực hiện tính năng này!' => '',
    'Chi tiết' => '',
    'Copyright' => '',
    'Công việc' => '',
    'Công việc yêu thích' => '',
    'Cung ứng nhân lực' => '',
    'Cảm ơn quý khách đã liên hệ! Chúng tôi sẽ phản hồi lại sớm nhất có thể!' => '',
    'Dịch vụ' => '',
    'Email' => '',
    'Giá trị cốt lõi' => '',
    'Giới thiệu' => '',
    'Gửi' => '',
    'Gửi liên hệ' => '',
    'Gửi Ý Kiến' => '',
    'Hybrid' => '',
    'Họ và tên' => '',
    'ID' => '',
    'Khác' => '',
    'Lao động' => '',
    'Liên hệ' => '',
    'Lắp ráp trong nước' => '',
    'Mã xác nhận' => '',
    'Mật khẩu cũ' => '',
    'Mật khẩu của bạn đã được khôi phục thành công!' => '',
    'Mật khẩu mới' => '',
    'Nhập khẩu' => '',
    'Nhập lại mật khẩu mới' => '',
    'Nội dung' => '',
    'Other posts' => '',
    'Product' => '',
    'Similar Products' => '',
    'Sản phẩm cùng danh mục' => '',
    'Số hỗn hợp' => '',
    'Số sàn' => '',
    'Số tự động' => '',
    'Số điện thoại' => '',
    'Thông báo tuyển dụng' => '',
    'Thương mại' => '',
    'Tin tức' => '',
    'Trang chủ' => '',
    'Trụ sở chính' => '',
    'Tìm kiếm' => '',
    'Tư vấn thiết kế, xây dựng' => '',
    'Tư vấn đầu tư' => '',
    'Tầm nhìn sứ mệnh' => '',
    'Về chúng tôi' => '',
    'Xe dầu' => '',
    'Xe xăng' => '',
    'Xe điện' => '',
    'Xin cấp phép' => '',
    'Ý kiến của Quý Khách đã được ghi nhận. Chúng tôi sẽ phản hồi sớm! Xin cảm ơn!' => '',
    'Đang cập nhật!' => '',
    'Đóng' => '',
    'Địa chỉ' => '',
    'Địa điểm' => '',
    'Đối tác' => '',
    'Created At' => '',
    'Description' => '',
    'Email List' => '',
    'Fax' => '',
    'Founding Date' => '',
    'Image Path' => '',
    'Music Genre ID' => '',
    'Name' => '',
    'Partner Code' => '',
    'Phone List' => '',
    'Position' => '',
    'Priority' => '',
    'Rank ID' => '',
    'Register Number' => '',
    'Representative' => '',
    'Singer ID' => '',
    'Song ID' => '',
    'Updated At' => '',
    'Username cannot be blank.' => 'Tên đăng nhập không được để trống',
    'Video ID' => '',
    'Website' => '',
];
