<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account not found!' => '',
    'Authorization code is required' => '',
    'Client id and Client secret is required' => '',
    'Invalid authorization code' => '',
    'Invalid captcha' => '',
    'Invalid input parameter' => '',
    'Invalid username password' => '',
    'Mps not response' => '',
    'Mật khẩu cũ không đúng, vui lòng thử lại!' => '',
    'Need permission to execute function.' => '',
    'Need post method to execute function.' => '',
    'Nhập lại mật khẩu mới chưa khớp!' => '',
    'No data' => '',
    'Out of promotion time' => '',
    'Over enjoy times' => '',
    'Over lucky code quota' => '',
    'Please login to perform this action' => '',
    'Promotion not found!' => '',
    'Require login.' => '',
    'Service is testing! Please come back later!' => '',
    'Successful' => '',
    'System is busy. Please try again later!' => '',
    'Thuê bao không tồn tại trên hệ thống!' => '',
    'Unknown method' => '',
    'Username and Password is required' => '',
    'Vui lòng nhập đủ thông tin!' => '',
    'Wrong client id and client secret' => '',
    'Your account is locked' => '',
    'Your account is not active' => '',
    'Đổi mật khẩu thành công!' => '',
];
